# Generated by Django 3.2.12 on 2022-05-09 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220421_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(help_text='用户ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='用户名', max_length=128)),
                ('user_psd', models.CharField(help_text='用户密码', max_length=128)),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除')),
                ('updated_tm', models.DateTimeField(auto_now=True)),
                ('created_tm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 16, 57, 54, 41749), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='UserRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(choices=[(1, 'vip'), (2, 'svip'), (3, 'ssvip')], help_text='用户角色')),
                ('user_rights', models.IntegerField(help_text='用户权限')),
                ('token', models.CharField(help_text='token', max_length=128)),
                ('updated_tm', models.DateTimeField(auto_now=True)),
                ('created_tm', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='用户ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo')),
            ],
        ),
    ]
