# Generated by Django 3.2.12 on 2022-05-09 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220509_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户基础信息', 'verbose_name_plural': '用户基础信息'},
        ),
        migrations.AlterModelOptions(
            name='userrights',
            options={'verbose_name': '用户权限信息', 'verbose_name_plural': '用户权限信息'},
        ),
        migrations.AlterField(
            model_name='productlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 17, 0, 11, 547271), verbose_name='date published'),
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
        migrations.AlterModelTable(
            name='userrights',
            table='user_rights',
        ),
    ]
