# Generated by Django 3.2.12 on 2022-04-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_productlist_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.productlist'),
        ),
    ]
